# Generated by Django 4.2.4 on 2023-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro', models.CharField(max_length=100)),
                ('aprovador', models.CharField(default='Antônio Rezende', max_length=100)),
                ('email', models.EmailField(default='antoniorezende@sicoob.com.br', max_length=254)),
                ('solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('email_solicitante', models.EmailField(blank=True, max_length=254, null=True)),
                ('reserva', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=100)),
                ('aprovador', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('email_solicitante', models.EmailField(blank=True, max_length=254, null=True)),
                ('reserva', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
