# Generated by Django 4.2.4 on 2023-08-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_salas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carros',
            new_name='Carro',
        ),
        migrations.RenameModel(
            old_name='Salas',
            new_name='Sala',
        ),
    ]
