# Generated by Django 4.2.4 on 2024-06-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reserva.resources'),
        ),
    ]
