# Generated by Django 4.2.4 on 2024-06-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_carro_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='type',
        ),
        migrations.AlterField(
            model_name='carro',
            name='carro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reserva.resources'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='hora',
            field=models.JSONField(),
        ),
    ]
