# Generated by Django 4.2.4 on 2023-08-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_aprovador'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprovador',
            name='primeiro_acesso',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
