# Generated by Django 4.2.4 on 2024-06-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_remove_carro_type_alter_carro_carro_alter_carro_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='carro',
        ),
    ]
