# Generated by Django 4.2.4 on 2024-06-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_remove_carro_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='carro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.resources'),
        ),
    ]
