# Generated by Django 4.2.4 on 2023-08-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_carro_aprovado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aprovador',
        ),
        migrations.AddField(
            model_name='carro',
            name='horaEnd',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='horaInit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='horaEnd',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='horaInit',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
