# Generated by Django 4.2.4 on 2023-09-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_rename_reserva_carro_dataend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='dataEnd',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='dataEnd',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='dataInit',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='horaEnd',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='horaInit',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='dataInit',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='horaEnd',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='horaInit',
        ),
        migrations.AddField(
            model_name='carro',
            name='hora',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='hora',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
