# Generated by Django 4.2.2 on 2023-09-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0011_rename_dataend_carro_data_rename_dataend_sala_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
